// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package matcolor

const (
	Version = "v0.9.0"
	GitCommit = "894d89c" // the commit JUST BEFORE the release
	VersionDate = "2023-08-18 20:27" // UTC
)

