// Code generated by "goki version"; DO NOT EDIT.

package matcolor

const (
	// Version is the version of this package being used
	Version = "v0.9.37"
	// GitCommit is the commit just before the latest version commit
	GitCommit = "2d6f63b"
	// VersionDate is the date-time of the latest version commit in UTC (in the format 'YYYY-MM-DD HH:MM', which is the Go format '2006-01-02 15:04')
	VersionDate = "2023-12-26 23:30"
)
